"""update user table

Revision ID: 35d52e394da1
Revises: 8f5ffba370ee
Create Date: 2024-09-25 06:58:12.361285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d52e394da1'
down_revision = '8f5ffba370ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.Text(), nullable=False))
        batch_op.drop_column('Password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Password', sa.TEXT(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
